export const BIND_CURRENT = 'BIND_CURRENT';
export const BIND_MAIN='BIND_MAIN';
export const BIND_DLG_REGISTER_WORD='BIND_DLG_REGISTER_WORD';
export const BIND_DLG_REGISTER_SENTENCE='BIND_DLG_REGISTER_SENTENCE';
export const BIND_DLG_VIEW_WORD_DETAILS='BIND_DLG_VIEW_WORD_DETAILS';
export const BIND_VALUE_WORDID="BIND_VALUE_WORDID";
export const BIND_SCRIPT_SELECTED="BIND_SCRIPT_SELECTED";