server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.88.116:33306/bandlanguagesite?serverTimezone=Asia/Shanghai&characterEncoding=utf8&tinyInt1isBit=false&useUnicode=true
      url: jdbc:mysql://127.0.0.1:3306/bandlanguagesite?serverTimezone=Asia/Shanghai&characterEncoding=utf8&tinyInt1isBit=false&useUnicode=true
      username: root
      password: liwei666
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 0
#    host: 192.168.88.116
    host: 127.0.0.1
    port: 6379
    # 如果未单独配置默认为空即可
#    password: liwei666
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis-plus:
  type-aliases-package: com.bandlanguage.bandlanguagesite.model.entity
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/*.xml

bandlanguagesite:
  jwt:
    secret: www.wetoband.com
    # token有效时长，7天，单位秒
    expire: 604800
    header: authorization

logging:
  level:
    com:
      bandlanguage:
        bandlanguagesite:
          mapper: debug
